travis:
  secure:
    BINSTAR_TOKEN: A1Cgyyt8WwzVnSskGXYx/I43zU/RzDL6rBQqMAzkyzraxTt84/J1KdQqDEA7AFicWtuEcIiOQ/2ycDEMYI0s7j8+qAeT+VqNfTAv4SugYB1YdonaB69XsLckNt9OvYb/DcK0hmqbUXndouhdVKXzxylyBr1G9axyj9Wnh7Ps4Kxkj3z6MAxgDu9i9wAdDJGewbsKr2Cki9TPwGlHYHT2ataJPH6XDo1PhN7jiN2xwPr82hrUOHy49WR4cQ1KhKnXnZllD1d/XLONvj6QfyBfuwbelEEANr30sN+s41NOPW/XbvdjuzBnDbk7Ov7m1k2RVibUez3iu2YnXUb3e34KHHW9gIiD/PB10PtrbWkFFnILlL655tmartHyb1E6PUQTqQUvopQy7nf+30zey/PoDzicoYMOhgGB8vHHfHETon+CM4W+1nuQ74/pczSialYmMjbd1IYKXp4zc80+0H+ABsAEwsBflO974U0on1J0OE+b1m/kcgAEe13aK3tat8GqybioC6lB3whqD9KB6rYQWuEtk2MMX9WZnUBdachEBWsPUaXw+gelqCiWimIzjiNpyO9IiBHewb3yYLYtTB14iQN9e1yLYP+gSwT9l+cMgf7mW1EAxSvocl/b1vE2Kj4DDI8sUcPS6avXAJHZSRR23Fkly/8sgZLGriVNSprUVe0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
