appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 7hsuNQ0ylMcR4nnX/CA/VrvKgs4vQbwRoYrFtNzm2bVMNxnPoGSPYSldwvXzUcCpTxljiYg4Jj2alI/glKBRXUYUk9ISjU+jtjIkIMZOPlGEqyjxqWhfE0o9nJ8NTK1EO7X+iu7CcD6J2OEoqD5JxpshA15zWuZElyq2D2wISnM7Tb5TqJpJhFZ7hVblrBlnHBldVqPvj/ywoqnWYyCWXROQZ2sE4NFS3Toi7QBH53fGWclk/8LXWSGHwoxEMJ7THaeZOL37Z07Jz/TBNQ6ybhfl+bGKe4nBCcdWr4szo3r3lB32CR2W1tc3TctUP+j09AEx+kusz3xrJI46uSGW56+iXbb5071hfwPxVfvWTII6XFKkMa5X/F/A9xyGEexvvbydMUcNkeytQhluGpCHAXN6rjcSRZSxig9p4kvMB/Duw+r9fWmhJ23PgSmqMo+Gks/eVKqGxT34BGj0ubPjl4K+Ykh0zBAP/VbzriE3UcmUE+zjSdeoPR3zxUsYsUZHwlVBnliL+jt5iefpqw5vjIjoeyVHHJe13FtSgAq/+KGz/kVOIaaR/A61Ps3RT63qMmPJLT2wGTyP3fpTv8gbdVZlXzwKmbOLN1UQ8355HYqUaQB9z3YvYuPwexK2BPy35hAjBYRvGZaCfHlLvbp2izqT71Kkkc52M83XwaswP1s=}
